language: python
python:
  - 3.4
install:
  - sudo apt-get install git
  - pip3 install beautifulsoup4
  - pip3 install pelican
  - pip3 install ghp-import
script:
  - python gen_yaogu.py
  - python gen_yaogu2.py
  - cd web2 && make publish
after_success:
  - echo OK
  - cp 404.html web/.
  - ghp-import -n web2/output -m "update by travis-ci"
  - git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
after_failure:
  - echo failed
